**Importing Essential Libraries**

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

**Importing Dataset**

In [3]:
df=pd.read_excel("/content/04-01-Financial Sample Data.xlsx")

In [4]:
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Menufacturing Cost,Sale Price,Gross Sales,Discount,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,United States of America,Paseo,Low,3450.0,10,34500.0,350,1207500.0,48300.00,1159200.00,897000.0,262200.00,41821,7,July,2014
1,Small Business,Canada,Montana,Medium,3802.5,5,19012.5,300,1140750.0,102667.50,1038082.50,950625.0,87457.50,41730,4,April,2014
2,Small Business,Canada,Velo,Medium,3793.5,120,455220.0,300,1138050.0,102424.50,1035625.50,948375.0,87250.50,41821,7,July,2014
3,Government,Germany,Velo,Low,2966.0,120,355920.0,350,1038100.0,20762.00,1017338.00,771160.0,246178.00,41548,10,October,2013
4,Government,Germany,Amarilla,Low,2966.0,260,771160.0,350,1038100.0,20762.00,1017338.00,771160.0,246178.00,41548,10,October,2013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699,Government,France,Montana,High,293.0,5,1465.0,7,2051.0,287.14,1763.86,1465.0,298.86,41671,2,February,2014
700,Government,United States of America,Carretera,Medium,263.0,3,789.0,7,1841.0,110.46,1730.54,1315.0,415.54,41579,11,November,2013
701,Government,Germany,Carretera,High,280.0,3,840.0,7,1960.0,274.40,1685.60,1400.0,285.60,41974,12,December,2014
702,Government,Germany,VTT,High,280.0,250,70000.0,7,1960.0,274.40,1685.60,1400.0,285.60,41974,12,December,2014
703,Government,Canada,Paseo,Medium,257.0,10,2570.0,7,1799.0,143.92,1655.08,1285.0,370.08,41760,5,May,2014

**Data Cleaning**

In [ ]:
df.dtypes

Segment                 object
Country                 object
Product                 object
Discount Band           object
Units Sold             float64
Manufacturing Price      int64
Menufacturing Cost     float64
Sale Price               int64
Gross Sales            float64
Discount               float64
 Sales                 float64
COGS                   float64
Profit                 float64
Date                     int64
Month Number             int64
Month Name              object
Year                     int64
dtype: object

In [ ]:
df.isnull().sum()

Segment                 0
Country                 0
Product                 0
Discount Band          55
Units Sold              0
Manufacturing Price     0
Menufacturing Cost      0
Sale Price              0
Gross Sales             0
Discount                0
 Sales                  0
COGS                    0
Profit                  0
Date                    0
Month Number            0
Month Name              0
Year                    0
dtype: int64

**coverting date number into real date**

In [5]:
df['RealDate'] = df['Date'].apply(lambda x: datetime(1900,1,1) + timedelta(days=x - 2))

In [6]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Menufacturing Cost,Sale Price,Gross Sales,Discount,Sales,COGS,Profit,Date,Month Number,Month Name,Year,RealDate
0,Government,United States of America,Paseo,Low,3450.0,10,34500.0,350,1207500.0,48300.0,1159200.0,897000.0,262200.0,41821,7,July,2014,2014-07-01
1,Small Business,Canada,Montana,Medium,3802.5,5,19012.5,300,1140750.0,102667.5,1038082.5,950625.0,87457.5,41730,4,April,2014,2014-04-01
2,Small Business,Canada,Velo,Medium,3793.5,120,455220.0,300,1138050.0,102424.5,1035625.5,948375.0,87250.5,41821,7,July,2014,2014-07-01
3,Government,Germany,Velo,Low,2966.0,120,355920.0,350,1038100.0,20762.0,1017338.0,771160.0,246178.0,41548,10,October,2013,2013-10-01
4,Government,Germany,Amarilla,Low,2966.0,260,771160.0,350,1038100.0,20762.0,1017338.0,771160.0,246178.0,41548,10,October,2013,2013-10-01

**Drop unnecessary columns,  manufactiring price in not correct**

In [7]:
df.drop('Menufacturing Cost', axis=1, inplace=True)

In [8]:
df.drop('Manufacturing Price', axis=1, inplace=True)

**Creating new column**

In [11]:
df['Manufacturing Price']=df.COGS/df['Units Sold']

In [12]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Sale Price,Gross Sales,Discount,Sales,COGS,Profit,Date,Month Number,Month Name,Year,RealDate,Manufacturing Price
0,Government,United States of America,Paseo,Low,3450.0,350,1207500.0,48300.0,1159200.0,897000.0,262200.0,41821,7,July,2014,2014-07-01,260.0
1,Small Business,Canada,Montana,Medium,3802.5,300,1140750.0,102667.5,1038082.5,950625.0,87457.5,41730,4,April,2014,2014-04-01,250.0
2,Small Business,Canada,Velo,Medium,3793.5,300,1138050.0,102424.5,1035625.5,948375.0,87250.5,41821,7,July,2014,2014-07-01,250.0
3,Government,Germany,Velo,Low,2966.0,350,1038100.0,20762.0,1017338.0,771160.0,246178.0,41548,10,October,2013,2013-10-01,260.0
4,Government,Germany,Amarilla,Low,2966.0,350,1038100.0,20762.0,1017338.0,771160.0,246178.0,41548,10,October,2013,2013-10-01,260.0

**Reposition new column**

In [13]:
manufacturing_price = df.pop('Manufacturing Price')
df.insert(5, 'Manufacturing Price', manufacturing_price)

In [14]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discount,Sales,COGS,Profit,Date,Month Number,Month Name,Year,RealDate
0,Government,United States of America,Paseo,Low,3450.0,260.0,350,1207500.0,48300.0,1159200.0,897000.0,262200.0,41821,7,July,2014,2014-07-01
1,Small Business,Canada,Montana,Medium,3802.5,250.0,300,1140750.0,102667.5,1038082.5,950625.0,87457.5,41730,4,April,2014,2014-04-01
2,Small Business,Canada,Velo,Medium,3793.5,250.0,300,1138050.0,102424.5,1035625.5,948375.0,87250.5,41821,7,July,2014,2014-07-01
3,Government,Germany,Velo,Low,2966.0,260.0,350,1038100.0,20762.0,1017338.0,771160.0,246178.0,41548,10,October,2013,2013-10-01
4,Government,Germany,Amarilla,Low,2966.0,260.0,350,1038100.0,20762.0,1017338.0,771160.0,246178.0,41548,10,October,2013,2013-10-01

In [15]:
df.drop('Date', axis=1, inplace=True)

df.to_csv("financial_sample_week5.csv", index= False)

In [20]:
df.to_csv("financial_sample_week5.csv", index= False)
from google.colab import files
files.download('financial_sample_week5.csv')